cBnivL = {}
local gl = GetLocale()

cBnivL.Search = SEARCH
cBnivL.Armor = GetItemClassInfo(4)
cBnivL.BattlePet = GetItemClassInfo(17)
cBnivL.Consumables = GetItemClassInfo(0)
cBnivL.Gem = GetItemClassInfo(3)
cBnivL.Quest = GetItemClassInfo(12)
cBnivL.Trades = GetItemClassInfo(7)
cBnivL.Weapon = GetItemClassInfo(2)
cBnivL.bagCaptions = {
	["cBniv_Bank"] 			= BANK,
	["cBniv_BankReagent"]	= REAGENT_BANK,
	["cBniv_BankSets"]		= LOOT_JOURNAL_ITEM_SETS,
	["cBniv_BankArmor"]		= BAG_FILTER_EQUIPMENT,
	["cBniv_BankGem"]		= AUCTION_CATEGORY_GEMS,
	["cBniv_BankQuest"]		= AUCTION_CATEGORY_QUEST_ITEMS,
	["cBniv_BankTrade"]		= BAG_FILTER_TRADE_GOODS,
	["cBniv_BankCons"]		= BAG_FILTER_CONSUMABLES,
	["cBniv_BankArtifact"]  = ARTIFACT_POWER,
	["cBniv_Junk"]			= BAG_FILTER_JUNK,
	["cBniv_ItemSets"]		= LOOT_JOURNAL_ITEM_SETS,
	["cBniv_Armor"]			= BAG_FILTER_EQUIPMENT,
	["cBniv_Gem"]			= AUCTION_CATEGORY_GEMS,
	["cBniv_Quest"]			= AUCTION_CATEGORY_QUEST_ITEMS,
	["cBniv_Consumables"]	= BAG_FILTER_CONSUMABLES,
	["cBniv_Artifact"]      = ARTIFACT_POWER,
	["cBniv_TradeGoods"]	= BAG_FILTER_TRADE_GOODS,
	["cBniv_BattlePet"]		= AUCTION_CATEGORY_BATTLE_PETS,
	["cBniv_Bag"]			= INVENTORY_TOOLTIP,
	["cBniv_Keyring"]		= KEYRING,
}	


if gl == "deDE" then
	cBnivL.MarkAsNew = "Als neu markieren"
	cBnivL.MarkAsKnown = "Als bekannt markieren"
	cBnivL.bagCaptions.cBniv_Stuff = "Cooles Zeugs"
	cBnivL.bagCaptions.cBniv_NewItems = "Neue Items"
elseif gl == "ruRU" then
	cBnivL.MarkAsNew = "Перенести в Новые предметы"
	cBnivL.MarkAsKnown = "Перенести в Известные предметы"
	cBnivL.bagCaptions.cBniv_Stuff = "Разное"
	cBnivL.bagCaptions.cBniv_NewItems = "Новые предметы"
elseif gl == "koKR" then
	cBnivL.MarkAsNew = "Mark as New"
	cBnivL.MarkAsKnown = "Mark as Known"
	cBnivL.bagCaptions.cBniv_Stuff = "지정"
	cBnivL.bagCaptions.cBniv_NewItems = "신규"
elseif gl == "frFR" then
	cBnivL.MarkAsNew = "Marquer comme Neuf"
	cBnivL.MarkAsKnown = "Marquer comme Connu"
	cBnivL.bagCaptions.cBniv_Stuff = "Divers"
	cBnivL.bagCaptions.cBniv_NewItems = "Nouveaux Objets"
elseif gl == "itIT" then
    cBnivL.MarkAsNew = "Segna come Nuovo"
    cBnivL.MarkAsKnown = "Segna come Conosciuto"
	cBnivL.bagCaptions.cBniv_Stuff = "Cose Interessanti"
	cBnivL.bagCaptions.cBniv_NewItems = "Oggetti Nuovi"

----------------------------------------------------------zhCN----------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
elseif gl == "zhCN" then
	cBnivL.MarkAsNew = "标记为新增"
    cBnivL.MarkAsKnown = "标记为已知"
	cBnivL.bagCaptions.cBniv_Stuff = "施法材料"
	cBnivL.bagCaptions.cBniv_NewItems = "新增"
	cBnivL['Toggle unlocked status.'] = "切换解锁状态."
	cBnivL['Toggle the "New Items" filter.'] = '切换 "新增" 标签显示状态.'
	cBnivL['Toggle the "Trade Goods" filter .'] = '切换 "商品" 标签显示状态.'
	cBnivL['Toggle the "Armor and Weapons" filter .'] = '切换 "装备" 标签显示状态.'
	cBnivL['Toggle the "Gem" filter .'] = '切换 "宝石" 标签显示状态.'
	cBnivL['Toggle the "Junk" filter.'] = '切换 "垃圾" 标签显示状态.'
	cBnivL['Toggle the "ItemSets" filters.'] = '切换 "套装" 标签显示状态.'
	cBnivL['Toggle the "Consumables" filters.'] = '切换 "消耗品" 标签显示状态.'
	cBnivL['Toggle the "Artifact" filters.'] = '切换 "神器能量" 标签显示状态.'
	cBnivL['Toggle the "Quest" filters.'] = '切换 "任务" 标签显示状态.'
	cBnivL['Toggle black bank background color.'] = '切换 黑色银行背景.'
	cBnivL['Toggle bank filtering.'] = '切换银行标签显示状态.'
	cBnivL['Toggle empty bagspace compression.'] = '切换背包空余格数显示状态.'
	cBnivL['Toggle auto sorting the bags.'] = '切换背包排序.'
	cBnivL['Toggle auto sorting the bank.'] = '切换银行排序.'
	cBnivL['Set the overall scale.'] = '设置缩放大小.'
	cBnivL['Add a custom container.'] = '添加一个自定义标签.'
	cBnivL['Remove a custom container.'] = '删除一个自定义标签.'
	cBnivL['List all custom containers.'] = '列出所有自定义标签.'
	cBnivL['Toggle buttons to move custom containers (up, down, left, right).'] = '显示按钮移动自定义分类(上, 下, 左, 右).'
	cBnivL['Changes the filter priority of a custom container.'] = '更改自定义分类优先级.'
	cBnivL['Show custom containers in the bank too.'] = '在银行中显示自定义标签.'
	cBnivL['You have to specify a name, e.g.'] = '必须指定一个分类名称,例如:'
	cBnivL['There is no custom container named'] = '该自定义分类不存在'
	cBnivL['There is custom container named'] = '请勿重复添加相同分类 '
	cBnivL['The "New Items" filter is now '] = '"新增" 标签显示状态 '
	cBnivL['The "Trade Goods" filter is now '] = '"商品" 标签显示状态 '
	cBnivL['The "Armor and Weapons" filter is now '] = '"装备" 标签显示状态 '
	cBnivL['The "Gem and Weapons" filter is now '] = '"宝石" 标签显示状态 '
	cBnivL['The "Junk" filter is now '] = '"垃圾" 标签显示状态 '
	cBnivL['The "ItemSets" filters are now '] = '"套装" 标签显示状态 '
	cBnivL['The "Consumables" filters are now '] = '"消耗品" 标签显示状态 '
	cBnivL['The "Artifact" filters are now '] = '"神器能量" 标签显示状态 '
	cBnivL['The "Quest" filters are now '] = '"任务" 标签显示状态 '
	cBnivL['Black background color for the bank is now '] = '黑色银行背景 '
	cBnivL['Bank filtering is now '] = '银行标签显示状态 '
	cBnivL['. Reload your UI for this change to take effect!'] = '. /Reload 重载插件后生效!'
	cBnivL['Empty bagspace compression is now '] = '背包空余格数显示状态 '
	cBnivL['Movable bags are now '] = '[背包]解锁 '
	cBnivL['Auto sorting bags is now '] = '背包排序 '
	cBnivL['Auto sorting bank is now '] = '银行排序 '
	cBnivL['Overall scale has been set to '] = '背包缩放:'
	cBnivL['You have to specify a value, e.g. '] = '你必须指定一个缩放比 ,例如:'
	cBnivL['The new custom container has been created. Reload your UI for this change to take effect!'] = '已成功添加自定义标签. /Reload 重载插件后生效!'
	cBnivL['A custom container with this name already exists.'] = '请勿重复添加相同分类.'
	cBnivL['The specified custom container has been removed. Reload your UI for this change to take effect!'] = '已成功移除自定义标签. /Reload 重载插件后生效!'
	cBnivL['There are '] = '总计'
	cBnivL[' custom containers.'] = '个自定义分类'
	cBnivL['Custom container movers are now '] = '[自定义分类]解锁 '
	cBnivL['The priority of the specified custom container has been set to '] = '已将指定的自定义分类优先级设置为 '
	cBnivL['Display of custom containers in the bank is now '] = '显示银行自定义分类 '	
	cBnivL['Reset New'] = '刷新'	
	cBnivL['Toggle Bags'] = '背包'	
	cBnivL['Restack'] = '整理'	
	cBnivL['Options'] = '设置'	
	cBnivL['Sell Junk '] = '售卖垃圾 '	
	cBnivL['Ctrl + Alt + Right Click an item to assign category'] = 'Ctrl + Alt + 右键单击一个物品进行分类'	
	cBnivL['Vendor trash sold: '] = '出售垃圾: '
----------------------------------------------------------zhTW-----------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------
elseif gl == "zhTW" then
	cBnivL.MarkAsNew = "Mark as New"
	cBnivL.MarkAsKnown = "Mark as Known"
	cBnivL.bagCaptions.cBniv_Stuff = "施法材料"
	cBnivL.bagCaptions.cBniv_NewItems = "新增"	
	cBnivL['Toggle unlocked status.'] = "切換解鎖狀態."
	cBnivL['Toggle the "New Items" filter.'] = '切換 "新增" 標簽顯示狀態.'
	cBnivL['Toggle the "Trade Goods" filter .'] = '切換 "商品" 標簽顯示狀態.'
	cBnivL['Toggle the "Armor and Weapons" filter .'] = '切換 "裝備" 標簽顯示狀態.'
	cBnivL['Toggle the "Gem" filter .'] = '切換 "寶石" 標簽顯示狀態.'
	cBnivL['Toggle the "Junk" filter.'] = '切換 "垃圾" 標簽顯示狀態.'
	cBnivL['Toggle the "ItemSets" filters.'] = '切換 "套裝" 標簽顯示狀態.'
	cBnivL['Toggle the "Consumables" filters.'] = '切換 "消耗品" 標簽顯示狀態.'
	cBnivL['Toggle the "Artifact" filters.'] = '切換 "神器能量" 標簽顯示狀態.'
	cBnivL['Toggle the "Quest" filters.'] = '切換 "任務" 標簽顯示狀態.'
	cBnivL['Toggle black bank background color.'] = '切換 黑色銀行背景.'
	cBnivL['Toggle bank filtering.'] = '切換銀行標簽顯示狀態.'
	cBnivL['Toggle empty bagspace compression.'] = '切換背包空余格數顯示狀態.'
	cBnivL['Toggle auto sorting the bags.'] = '切換背包排序.'
	cBnivL['Toggle auto sorting the bank.'] = '切換銀行排序.'
	cBnivL['Set the overall scale.'] = '設置縮放大小.'
	cBnivL['Add a custom container.'] = '添加壹個自定義標簽.'
	cBnivL['Remove a custom container.'] = '刪除壹個自定義標簽.'
	cBnivL['List all custom containers.'] = '列出所有自定義標簽.'
	cBnivL['Toggle buttons to move custom containers (up, down, left, right).'] = '顯示按鈕移動自定義分類(上, 下, 左, 右).'
	cBnivL['Changes the filter priority of a custom container.'] = '更改自定義分類優先級.'
	cBnivL['Show custom containers in the bank too.'] = '在銀行中顯示自定義標簽.'
	cBnivL['You have to specify a name, e.g.'] = '必須指定壹個分類名稱,例如:'
	cBnivL['There is no custom container named'] = '該自定義分類不存在'
	cBnivL['There is custom container named'] = '請勿重復添加相同分類 '
	cBnivL['The "New Items" filter is now '] = '"新增" 標簽顯示狀態 '
	cBnivL['The "Trade Goods" filter is now '] = '"商品" 標簽顯示狀態 '
	cBnivL['The "Armor and Weapons" filter is now '] = '"裝備" 標簽顯示狀態 '
	cBnivL['The "Gem and Weapons" filter is now '] = '"寶石" 標簽顯示狀態 '
	cBnivL['The "Junk" filter is now '] = '"垃圾" 標簽顯示狀態 '
	cBnivL['The "ItemSets" filters are now '] = '"套裝" 標簽顯示狀態 '
	cBnivL['The "Consumables" filters are now '] = '"消耗品" 標簽顯示狀態 '
	cBnivL['The "Artifact" filters are now '] = '"神器能量" 標簽顯示狀態 '
	cBnivL['The "Quest" filters are now '] = '"任務" 標簽顯示狀態 '
	cBnivL['Black background color for the bank is now '] = '黑色銀行背景 '
	cBnivL['Bank filtering is now '] = '銀行標簽顯示狀態 '
	cBnivL['. Reload your UI for this change to take effect!'] = '. /Reload 重載插件後生效!'
	cBnivL['Empty bagspace compression is now '] = '背包空余格數顯示狀態 '
	cBnivL['Movable bags are now '] = '[背包]解鎖 '
	cBnivL['Auto sorting bags is now '] = '背包排序 '
	cBnivL['Auto sorting bank is now '] = '銀行排序 '
	cBnivL['Overall scale has been set to '] = '背包縮放:'
	cBnivL['You have to specify a value, e.g. '] = '妳必須指定壹個縮放比 ,例如:'
	cBnivL['The new custom container has been created. Reload your UI for this change to take effect!'] = '已成功添加自定義標簽. /Reload 重載插件後生效!'
	cBnivL['A custom container with this name already exists.'] = '請勿重復添加相同分類.'
	cBnivL['The specified custom container has been removed. Reload your UI for this change to take effect!'] = '已成功移除自定義標簽. /Reload 重載插件後生效!'
	cBnivL['There are '] = '總計'
	cBnivL[' custom containers.'] = '個自定義分類'
	cBnivL['Custom container movers are now '] = '[自定義分類]解鎖 '
	cBnivL['The priority of the specified custom container has been set to '] = '已將指定的自定義分類優先級設置為 '
	cBnivL['Display of custom containers in the bank is now '] = '顯示銀行自定義分類 '	
	cBnivL['Reset New'] = '刷新'	
	cBnivL['Toggle Bags'] = '背包'	
	cBnivL['Restack'] = '整理'	
	cBnivL['Options'] = '設置'	
	cBnivL['Sell Junk '] = '售賣垃圾 '	
	cBnivL['Ctrl + Alt + Right Click an item to assign category'] = 'Ctrl + Alt + 右鍵單擊壹個物品進行分類'	
	cBnivL['Vendor trash sold: '] = '出售垃圾: '
----------------------------------------------------------enUS-----------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------
else
	cBnivL.MarkAsNew = "Mark as New"
	cBnivL.MarkAsKnown = "Mark as Known"
	cBnivL.bagCaptions.cBniv_Stuff = "Cool Stuff"
	cBnivL.bagCaptions.cBniv_NewItems = "New Items"
	cBnivL['Toggle unlocked status.'] = "Toggle unlocked status."
	cBnivL['Toggle the "New Items" filter.'] = 'Toggle the "New Items" filter.'
	cBnivL['Toggle the "Trade Goods" filter .'] = 'Toggle the "Trade Goods" filter .'
	cBnivL['Toggle the "Armor and Weapons" filter .'] = 'Toggle the "Armor and Weapons" filter .'
	cBnivL['Toggle the "Gem" filter .'] = 'Toggle the "Gem" filter .'
	cBnivL['Toggle the "Junk" filter.'] = 'Toggle the "Junk" filter.'
	cBnivL['Toggle the "ItemSets" filters.'] = 'Toggle the "ItemSets" filters.'
	cBnivL['Toggle the "Consumables" filters.'] = 'Toggle the "Consumables" filters.'
	cBnivL['Toggle the "Artifact" filters.'] = 'Toggle the "Artifact" filters.'
	cBnivL['Toggle the "Quest" filters.'] = 'Toggle the "Quest" filters.'
	cBnivL['Toggle black bank background color.'] = 'Toggle black bank background color.'
	cBnivL['Toggle bank filtering.'] = 'Toggle bank filtering.'
	cBnivL['Toggle empty bagspace compression.'] = 'Toggle empty bagspace compression.'
	cBnivL['Toggle auto sorting the bags.'] = 'Toggle auto sorting the bags.'
	cBnivL['Toggle auto sorting the bank.'] = 'Toggle auto sorting the bank.'
	cBnivL['Set the overall scale.'] = 'Set the overall scale.'
	cBnivL['Add a custom container.'] = 'Add a custom container.'
	cBnivL['Remove a custom container.'] = 'Remove a custom container.'
	cBnivL['List all custom containers.'] = 'List all custom containers.'
	cBnivL['Toggle buttons to move custom containers (up, down, left, right).'] = 'Toggle buttons to move custom containers (up, down, left, right).'
	cBnivL['Changes the filter priority of a custom container.'] = "Changes the filter priority of a custom container. High priority prevents items from being classified as junk or new, low priority doesn't."
	cBnivL['Show custom containers in the bank too.'] = 'Show custom containers in the bank too.'
	cBnivL['You have to specify a name, e.g.'] = 'You have to specify a name, e.g.'
	cBnivL['There is no custom container named'] = 'There is no custom container named'
	cBnivL['There is custom container named'] = 'There is custom container named'
	cBnivL['The "New Items" filter is now '] = 'The "New Items" filter is now '
	cBnivL['The "Trade Goods" filter is now '] = 'The "Trade Goods" filter is now '
	cBnivL['The "Armor and Weapons" filter is now '] = 'The "Armor and Weapons" filter is now '
	cBnivL['The "Gem and Weapons" filter is now '] = 'The "Gem and Weapons" filter is now '
	cBnivL['The "Junk" filter is now '] = 'The "Junk" filter is now '
	cBnivL['The "ItemSets" filters are now '] = 'The "ItemSets" filters are now '
	cBnivL['The "Consumables" filters are now '] = 'The "Consumables" filters are now '
	cBnivL['The "Artifact" filters are now '] = 'The "Artifact" filters are now '
	cBnivL['The "Quest" filters are now '] = 'The "Quest" filters are now '
	cBnivL['Black background color for the bank is now '] = 'Black background color for the bank is now '
	cBnivL['Bank filtering is now '] = 'Bank filtering is now '
	cBnivL['. Reload your UI for this change to take effect!'] = '. Reload your UI for this change to take effect!'
	cBnivL['Empty bagspace compression is now '] = 'Empty bagspace compression is now '
	cBnivL['Movable bags are now '] = 'Movable bags are now '
	cBnivL['Auto sorting bags is now '] = 'Auto sorting bags is now '
	cBnivL['Auto sorting bank is now '] = 'Auto sorting bank is now '
	cBnivL['Overall scale has been set to '] = 'Overall scale has been set to '
	cBnivL['You have to specify a value, e.g. '] = 'You have to specify a value, e.g. '
	cBnivL['The new custom container has been created. Reload your UI for this change to take effect!'] = 'The new custom container has been created. Reload your UI for this change to take effect!'
	cBnivL['A custom container with this name already exists.'] = 'A custom container with this name already exists.'
	cBnivL['The specified custom container has been removed. Reload your UI for this change to take effect!'] = 'The specified custom container has been removed. Reload your UI for this change to take effect!'
	cBnivL['There are '] = 'There are '
	cBnivL[' custom containers.'] = ' custom containers.'
	cBnivL['Custom container movers are now '] = 'Custom container movers are now '
	cBnivL['The priority of the specified custom container has been set to '] = 'The priority of the specified custom container has been set to '
	cBnivL['Display of custom containers in the bank is now '] = 'Display of custom containers in the bank is now '
	cBnivL['Reset New'] = 'Reset New'
	cBnivL['Toggle Bags'] = 'Toggle Bags'
	cBnivL['Restack'] = 'Restack'	
	cBnivL['Options'] = 'Options'
	cBnivL['Sell Junk '] = 'Sell Junk '
	cBnivL['Ctrl + Alt + Right Click an item to assign category'] = 'Ctrl + Alt + Right Click an item to assign category'
	cBnivL['Vendor trash sold: '] = 'Vendor trash sold: '
end
